[package]
name = "nauka"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.4.4", features = ["derive"]}
num = "0.4.1"
num-derive = "0.4.0"
num-traits = "0.2.16"
sdl2 = {version = "0.35.2", features = ["bundled"]}
